numer_1 = int(input())
numer_2 = int(input())
numer_3 = int(input())
numer_4 = int(input())
numer_5 = int(input())
print("The smallest number =", min(numer_1, numer_2, numer_3, numer_4, numer_5))
print("The biggest number =", max(numer_1, numer_2, numer_3, numer_4, numer_5))